# -*- coding: utf-8 -*-
"""Visualisasi Statistik Pelaporan Barang Harian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGYBIfBT0EevQLR8JvW9rATqJgcQqbND

Import Library
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Data"""

df = pd.read_csv('/content/pelaporan_stats_harian.csv')

"""Make Plot"""

#Konversi Tanggal
df['date'] = pd.to_datetime(df['date'])

plt.figure(figsize=(14, 6))
sns.lineplot(data=df, x='date', y='incoming', label='Incoming')
sns.lineplot(data=df, x='date', y='processed', label='Processed')
sns.lineplot(data=df, x='date', y='outgoing', label='Outgoing')

plt.title('Statistik Pelaporan Barang Harian')
plt.xlabel('Date')
plt.ylabel('Total Quantity')
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.grid(True)
plt.show()

