# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5FlSsXLLRt9fCSmleBqnqThdsJDgd2y

Import Library
"""

import csv
import psycopg2

"""Bulk Insert Function"""

def get_or_create(cursor, table, column, value, cache, pk_column):
    if not value or value.strip() == '':
        return None

    if value in cache:
        return cache[value]

    cursor.execute(f"SELECT {pk_column} FROM {table} WHERE {column} = %s", (value,))
    result = cursor.fetchone()
    if result:
        cache[value] = result[0]
        return result[0]
    else:
        cursor.execute(f"INSERT INTO {table} ({column}) VALUES (%s) RETURNING {pk_column}", (value,))
        new_id = cursor.fetchone()[0]
        cache[value] = new_id
        return new_id

def bulk_insert_from_csv(file_path, connection):
    product_cache = {}
    unit_cache = {}
    vendor_cache = {}
    client_cache = {}
    manager_cache = {}

    with open(file_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        with connection.cursor() as cursor:
            for idx, row in enumerate(reader, start=1):
                transaction_time = row['Waktu'].strip()
                product_name = row['Nama Barang'].strip()
                jumlah_raw = row['Jumlah'].strip()
                quantity = int(jumlah_raw) if jumlah_raw != '' else 0
                unit_name = row['Unit satuan'].strip()
                vendor_name = row['Vendor'].strip()
                client_name = row['Client'].strip()
                manager_name = row['Di Proses Oleh'].strip()

                product_id = get_or_create(cursor, 'Product', 'name', product_name, product_cache, 'product_id')
                unit_id = get_or_create(cursor, 'Unit', 'name', unit_name, unit_cache, 'unit_id')
                vendor_id = get_or_create(cursor, 'Vendor', 'name', vendor_name, vendor_cache, 'vendor_id') if quantity > 0 else None
                client_id = get_or_create(cursor, 'Client', 'name', client_name, client_cache, 'client_id') if quantity < 0 else None
                manager_id = get_or_create(cursor, 'WarehouseManager', 'name', manager_name, manager_cache, 'manager_id')

                cursor.execute("""
                    INSERT INTO Transaction (
                        product_id, quantity, unit_id, transaction_time,
                        vendor_id, client_id, manager_id
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                """, (product_id, quantity, unit_id, transaction_time, vendor_id, client_id, manager_id))

                if idx % 10 == 0:
                    print(f"{idx} baris diproses...")

        connection.commit()
    print("Bulk insert selesai.")

if __name__ == "__main__":
    conn = psycopg2.connect(
        host="localhost",
        database="warehouse_project",
        user="postgres",
        password="admin123"
    )
    bulk_insert_from_csv("C:\\data.csv", conn)
    conn.close()